# Generated by Django 5.0.6 on 2024-06-27 15:46

import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import webapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория рецептов',
                'verbose_name_plural': 'Категории рецептов',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('cooking_steps', models.TextField(verbose_name='Шаги приготовления')),
                ('cooking_time', models.DurationField(verbose_name='Время приготовления (чч:мм:сс)')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=webapp.models.user_directory_path, verbose_name='Изображение блюда')),
                ('active', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
