# Generated by Django 5.0.6 on 2024-06-28 17:54

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to=webapp.models.user_directory_path, verbose_name='Изображение блюда'),
        ),
    ]
