# Generated by Django 5.0.6 on 2024-06-28 17:54

import django.db.models.deletion
import usersapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'О домочадце', 'verbose_name_plural': 'О домочадцах'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='вуафгде_avatar.jpg', upload_to=usersapp.models.user_directory_path, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Домочадец'),
        ),
    ]
